const testcases = [
    { "problemId": 1, "isHidden": false, "input": "[2,7,11,15]\n9", "output": "[0,1]" },
    { "problemId": 1, "isHidden": false, "input": "[3,2,4]\n6", "output": "[1,2]" },
    { "problemId": 1, "isHidden": false, "input": "[3,3]\n6", "output": "[0,1]" },
    { "problemId": 1, "isHidden": true, "input": "[-1,-2,-3,-4,-5]\n-8", "output": "[2,4]" },
    { "problemId": 1, "isHidden": true, "input": "[0,4,3,0]\n0", "output": "[0,3]" },
    { "problemId": 1, "isHidden": true, "input": "[1000000000,-1000000000]\n0", "output": "[0,1]" },

    { "problemId": 2, "isHidden": false, "input": "\"()[]{}\"", "output": "true" },
    { "problemId": 2, "isHidden": false, "input": "\"(]\"", "output": "false" },
    { "problemId": 2, "isHidden": false, "input": "\"([])\"", "output": "true" },
    { "problemId": 2, "isHidden": true, "input": "\"[\"", "output": "false" },
    { "problemId": 2, "isHidden": true, "input": "\"]\"", "output": "false" },
    { "problemId": 2, "isHidden": true, "input": "\"((((((()))))))\"", "output": "true" },
    { "problemId": 2, "isHidden": true, "input": "\"[(])\"", "output": "false" },

    { "problemId": 3, "isHidden": false, "input": "[-2,1,-3,4,-1,2,1,-5,4]", "output": "6" },
    { "problemId": 3, "isHidden": false, "input": "[1]", "output": "1" },
    { "problemId": 3, "isHidden": false, "input": "[5,4,-1,7,8]", "output": "23" },
    { "problemId": 3, "isHidden": true, "input": "[-1]", "output": "-1" },
    { "problemId": 3, "isHidden": true, "input": "[-5,-4,-3,-2,-1]", "output": "-1" },
    { "problemId": 3, "isHidden": true, "input": "[1,2,3,4,5]", "output": "15" },

    { "problemId": 4, "isHidden": false, "input": "[-1,0,3,5,9,12]\n9", "output": "4" },
    { "problemId": 4, "isHidden": false, "input": "[-1,0,3,5,9,12]\n2", "output": "-1" },
    { "problemId": 4, "isHidden": false, "input": "[5]\n5", "output": "0" },
    { "problemId": 4, "isHidden": true, "input": "[2,5]\n2", "output": "0" },
    { "problemId": 4, "isHidden": true, "input": "[2,5]\n5", "output": "1" },
    { "problemId": 4, "isHidden": true, "input": "[-10,-5,0,3,7,12]\n-5", "output": "1" },

    { "problemId": 5, "isHidden": false, "input": "[1,2,3,0,0,0]\n3\n[2,5,6]\n3", "output": "[1,2,2,3,5,6]" },
    { "problemId": 5, "isHidden": false, "input": "[1]\n1\n[]\n0", "output": "[1]" },
    { "problemId": 5, "isHidden": false, "input": "[0]\n0\n[1]\n1", "output": "[1]" },
    { "problemId": 5, "isHidden": true, "input": "[4,5,6,0,0,0]\n3\n[1,2,3]\n3", "output": "[1,2,3,4,5,6]" },
    { "problemId": 5, "isHidden": true, "input": "[-1,0,0,3,3,0,0,0]\n5\n[1,2,4]\n3", "output": "[-1,0,0,1,2,3,3,4]" },

    { "problemId": 6, "isHidden": false, "input": "[\"h\",\"e\",\"l\",\"l\",\"o\"]", "output": "[\"o\",\"l\",\"l\",\"e\",\"h\"]" },
    { "problemId": 6, "isHidden": false, "input": "[\"H\",\"a\",\"n\",\"n\",\"a\",\"h\"]", "output": "[\"h\",\"a\",\"n\",\"n\",\"a\",\"H\"]" },
    { "problemId": 6, "isHidden": false, "input": "[\"a\"]", "output": "[\"a\"]" },
    { "problemId": 6, "isHidden": true, "input": "[\"A\",\"B\"]", "output": "[\"B\",\"A\"]" },
    { "problemId": 6, "isHidden": true, "input": "[\"1\",\"2\",\"3\",\"4\"]", "output": "[\"4\",\"3\",\"2\",\"1\"]" },

    { "problemId": 7, "isHidden": false, "input": "121", "output": "true" },
    { "problemId": 7, "isHidden": false, "input": "-121", "output": "false" },
    { "problemId": 7, "isHidden": false, "input": "10", "output": "false" },
    { "problemId": 7, "isHidden": true, "input": "0", "output": "true" },
    { "problemId": 7, "isHidden": true, "input": "12321", "output": "true" },
    { "problemId": 7, "isHidden": true, "input": "2147483647", "output": "false" },

    { "problemId": 8, "isHidden": false, "input": "2", "output": "2" },
    { "problemId": 8, "isHidden": false, "input": "3", "output": "3" },
    { "problemId": 8, "isHidden": false, "input": "4", "output": "5" },
    { "problemId": 8, "isHidden": true, "input": "1", "output": "1" },
    { "problemId": 8, "isHidden": true, "input": "5", "output": "8" },
    { "problemId": 8, "isHidden": true, "input": "45", "output": "1836311903" },

    { "problemId": 9, "isHidden": false, "input": "[7,1,5,3,6,4]", "output": "5" },
    { "problemId": 9, "isHidden": false, "input": "[7,6,4,3,1]", "output": "0" },
    { "problemId": 9, "isHidden": false, "input": "[1,2]", "output": "1" },
    { "problemId": 9, "isHidden": true, "input": "[3,3,3,3]", "output": "0" },
    { "problemId": 9, "isHidden": true, "input": "[1,2,4,2,5,7,2,4,9,0]", "output": "8" },
    { "problemId": 9, "isHidden": true, "input": "[100]", "output": "0" },

    { "problemId": 10, "isHidden": false, "input": "[1,2,3,1]", "output": "true" },
    { "problemId": 10, "isHidden": false, "input": "[1,2,3,4]", "output": "false" },
    { "problemId": 10, "isHidden": false, "input": "[1,1,1,3,3,4,3,2,4,2]", "output": "true" },
    { "problemId": 10, "isHidden": true, "input": "[0]", "output": "false" },
    { "problemId": 10, "isHidden": true, "input": "[-1000000000,1000000000,-1000000000]", "output": "true" },
    { "problemId": 10, "isHidden": true, "input": "[5,4,3,2,1,0,-1]", "output": "false" }
]